// Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Preview durch <Strg><Shift>v

= Projekthandbuch
Xuezhi He <hexu1011@h-ka.de>
:doctype: book
:toc: left
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: highlight.js
:icons: font
// :kroki-server-url: https://kroki.io

// https://github.com/asciidoctor/asciidoctorj
// https://github.com/asciidoctor/asciidoctor-diagram
// http://de.plantuml.com/classes.html
// http://de.plantuml.com/component.html
// https://github.com/odrotbohm/asciidoctor-plantuml

IMPORTANT: Copyright (C) 2020 - present Jürgen Zimmermann, Hochschule Karlsruhe. +
           Free use of this software is granted under the terms of the
           GNU General Public License (GPL) v3. +
           For the full text of the license, see the http://www.gnu.org/licenses/gpl-3.0.html[license] file.

== Der Applikationsserver

=== Der Applikationsserver im Überblick

Use Cases

.Use Cases
[plantuml,use-cases,svg]
----
include::use-cases.plantuml[]
----

Komponentendiagramm

.Komponentendiagramm
[plantuml,komponenten,svg]
----
include::komponenten.plantuml[]
----

=== Die REST-Schnittstelle

."LaptopGetController" für Lesezugriffe an der REST-Schnittstelle
[plantuml,LaptopGetController,svg]
----
include::LaptopGetController.plantuml[]
----

."Sequenzdiagramm" mit den Methodenaufrufen
[plantuml,sequenzdiagramm,svg]
----
include::sequenzdiagramm.plantuml[]
----

."LaptopWriteController" für Schreibzugriffe an der REST-Schnittstelle
[plantuml,LaptopGetController,svg]
----
include::LaptopWriteController.plantuml[]
----

=== Die GraphQL-Schnittstelle

.LaptopQueryResolver für Lesezugriffe an der GraphQL-Schnittstelle
[plantuml,LaptopQueryResolver,svg]
----
include::LaptopQueryResolver.plantuml[]
----

.LaptopMutationResolver für Schreibzugriffe an der GraphQL-Schnittstelle
[plantuml,LaptopMutationResolver,svg]
----
include::LaptopMutationResolver.plantuml[]
----

=== Die Geschäftslogik

."LaptopReadService" von der Geschäftslogik
[plantuml,LaptopReadService,svg]
----
include::LaptopReadService.plantuml[]
----

."LaptopWriteService" von der Geschäftslogik
[plantuml,LaptopWriteService,svg]
----
include::LaptopWriteService.plantuml[]
----

=== Klasse für Entities

.Entity
[plantuml,Laptop,svg]
----
include::Laptop.plantuml[]
----

=== ER-Diagramm

.ER-Diagramm
[plantuml,ER-Diagramm,svg]
----
include::ER-Diagramm.plantuml[]
----

== Programmierrichtlinien für TypeScript und JavaScript

Für die Programmierung mit *TypeScript* und *JavaScript* sind folgende
Styleguides empfehlenswert:

[horizontal]
_E-Book zu TypeScript_:: https://github.com/gibbok/typescript-book
_Google_:: https://google.github.io/styleguide/tsguide.html
_Airbnb_:: https://github.com/airbnb/javascript
_Shopify_:: https://github.com/Shopify/javascript
_React bei Airbnb_:: https://github.com/airbnb/javascript/tree/master/react
_Angular_:: https://angular.io/docs/ts/latest/guide/style-guide.html
_Microsoft_:: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines

Von IBM und Red Hat gibt es bei GitHub _Node.js Reference Architecture_
https://github.com/nodeshift/nodejs-reference-architecture, wo alle möglichen
Aspekte bei der Softwareentwicklung mit Node berücksichtigt sind und
entsprechende Empfehlungen bzw. Best Practices beschrieben sind.
Diese Dokumentation muss man einfach gelesen haben. Ebenfalls empfehlenswert
ist https://github.com/goldbergyoni/nodebestpractices.
